### ISSUE TITLE
Modifying trackers ?

### ISSUE THREAD

**Issue by AnatoleLucet** [webtorrent/webtorrent-desktop#1701] opened 2019-09-17 11:48 UTC
**What version of this package are you using?**
`WebTorrent Version 0.21.0 (0.107.16) (64-bit)`

**What problem do you want to solve?**
I would want to be able to change trackers.

**What do you think is the correct solution to this problem?**
Maybe a window with text inputs to modify it ?
This window could be accessible via a right click on a specific torrent in the main list.

**Are you willing to submit a pull request to implement this change?**
I've already worked on Electron but I'm not a pro, so if someone describe me grossly what to do I may be able to do it.

**Comment by subins2000** [comment] 2020-07-19 18:01
PR #1836 addresses this. Possible duplicate of #881

**Comment by feross** [comment] 2020-11-23 20:45
This might be asking to change trackers for an individual torrent, but I'll consider it a duplicate of #881.

**Closed by feross** 2020-11-23 20:45 UTC
Labels: enhancement
