### ISSUE TITLE
Make WebTorrent into a Snap package.

### ISSUE THREAD

**Issue by AmirIqbal1** [webtorrent/webtorrent-desktop#1804] opened 2020-04-21 09:01 UTC
**What version of WebTorrent Desktop are you using?**
Latest - 0.21.0 (0.107.16)

**What operating system and version?**
Ubuntu 18.04

**What problem do you want to solve?**
Packaging and more access to different Linux users.

**What do you think is the correct solution to this problem?**
Package this app as a Snap package, installing correct dependencies. 

**Are you willing to submit a pull request to implement this change?**
Maybe, need more suggestions from other users.

**Comment by alxhotel** [comment] 2020-04-21 10:42
Duplicate of #1071

**Closed by alxhotel** 2020-04-21 10:42 UTC
