### ISSUE TITLE
Request to modify upload / download speed.

### ISSUE THREAD

**Issue by rlpalomo25** [webtorrent/webtorrent-desktop#1295] opened 2017-12-28 17:18 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)
**What operating system and version?**
Win7 64 Bits
**What did you do?**
Downloaded a torrent.
**What did you expect to happen?**
Being able to modify the upload and download speed.
**What actually happened?**
Unable to do so. There is no option to modify upload/download speed.

**Comment by bnjmnt4n** [comment] 2017-12-29 14:26
Closing this as a duplicate of #435. I don't think any of the WebTorrent Desktop contributors have time to implement this feature now, but feel free to send a PR if you can.

**Closed by bnjmnt4n** 2017-12-29 14:26 UTC
Labels: duplicate
