### ISSUE TITLE
Improvement. Arrows navigation when watching movie.

### ISSUE THREAD

**Issue by maciekpaprocki** [webtorrent/webtorrent-desktop#1515] opened 2018-11-27 17:28 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v0.99.4 - 2018-05-03

**What operating system and version?**
MacOS Mojave

**What did you do?**
Watching movie. 

**What did you expect to happen?**
Using horizontal arrows should move few seconds (10s) in right direction, moving vertical arrows should change sound level.

**What actually happened?**
Arrows are unresponsive. 

Best
Maciej

**Comment by mathiasvr** [comment] 2018-11-27 21:49
Closing as duplicate of #1395.

For now you have to use the shortcuts listed in the `Playback` menu.

**Closed by mathiasvr** 2018-11-27 21:49 UTC
