### ISSUE TITLE
Error: setMulticastInterface EADDRNOTAVAIL

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1935] opened 2021-05-14 15:18 UTC
**What version of WebTorrent Desktop are you using?**

0.24.0

**What operating system and version?**

Windows

**What happened?**

From WebTorrent Desktop telemetry logs:

```
Processes: window, platforms: win32, versions: 0.21.0 0.24.0
Error: setMulticastInterface EADDRNOTAVAIL
    at Socket.setMulticastInterface (dgram.js:818:11)
    at that.update (...\node_modules\multicast-dns\index.js:141:12)
```

**Comment by alxhotel** [comment] 2021-05-21 09:48
I'm not able to reproduce this bug.

However, this bug seems to be come from the `multicast-dns` package. The bug could have already being fixed in the current `multicast-dns` version (7.2.2).

So I have opened a PR to update the `chromecasts` package to the latest `multicast-dns` version (https://github.com/mafintosh/chromecasts/pull/40).

In addition, there is a pending PR (https://github.com/mafintosh/multicast-dns/pull/50) in `multicast-dns` which adds a try-catch to handle these exceptions which also seem to help in these case.

**Closed** 2021-10-04 14:18 UTC
Labels: bug
