### ISSUE TITLE
The files are not sorted by name in expanded file list view

### ISSUE THREAD

**Issue by elsteelbrain** [webtorrent/webtorrent-desktop#1285] opened 2017-12-11 10:23 UTC
**What version of WebTorrent Desktop?**
Version 0.18.0 (0.98.5)
**What operating system and version?**
macOS High Sierra 10.13.1 (17B1003)
**What did you do?**
Added a torrent with multiple files to WebTorrent.
**What did you expect to happen?**
That the files will be sorted by name in expanded file list view of torrent.
**What actually happened?**
The files were not sorted by names.

**Comment by elsteelbrain** [comment] 2017-12-11 10:24
PR: https://github.com/webtorrent/webtorrent-desktop/pull/1284

**Comment by elsteelbrain** [comment] 2017-12-11 13:20
I just realized that while the PR fixes the problem in the file list it doesn't sort the order of files that is passed to the player. So, when you have multiple videos, the player will not follow the sorting order when loading next or previous video.

**Comment by bnjmnt4n** [comment] 2018-01-18 14:03
Marking this as a duplicate of #1185.

**Closed by bnjmnt4n** 2018-01-18 14:03 UTC
