### ISSUE TITLE
[Windows] External players don't open under the proper filename

### ISSUE THREAD

**Issue by Zyst** [webtorrent/webtorrent-desktop#1200] opened 2017-07-07 19:02 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)

**What operating system and version?**
Windows 10 Home 64 bit Version 1703

**What did you do?**
Selected to start playing a video through the local interface

**What did you expect to happen?**
The player would have access to the filename, which can be relevant for scripts such as [Subler](https://subler.org/).

![No filename](https://user-images.githubusercontent.com/3832380/27972830-52ae5784-631d-11e7-9db3-8de45a4505dd.png)

**What actually happened?**

It only opens with a generic name. I know sending the filename should be technically feasible because `youtube-dl` + `mpv` do that:

![Youtube-dl example](https://user-images.githubusercontent.com/3832380/27972902-8c2c29aa-631d-11e7-8edf-565aacad22db.png)

**Comment by Zyst** [comment] 2017-07-07 19:08
Same as my other issue:

Couldn't find a duplicate of this, I did go through all the open issues. I apologize if this is, however, a duplicate.

If so please link the relevant issue and close this one, I'll re-post the OP in that issue as well.

**Comment by feross** [comment] 2018-04-25 01:41
@Zyst Is there a command line argument that we can use to pass the name through to mpv?

**Comment by Zyst** [comment] 2018-04-25 04:10
Don't know, I know you can use `--title` to set the window title, but `name` does seems to be set to filename. 

I did go over the MPV docs but I couldn't find anything.

**Comment by hicom150** [comment] 2019-09-26 09:34
Duplicate of #1349 fixed in #1648

**Closed by hicom150** 2019-09-26 09:34 UTC
Labels: bug
