### ISSUE TITLE
Sort torrent's files by name instead of file size

### ISSUE THREAD

**Issue by FlaggedBrad** [webtorrent/webtorrent-desktop#1243] opened 2017-09-24 05:12 UTC
Why are the torrent's files sorted by the size of the files, instead of the names of the actual files? This causes shows in a series to be mixed up and disorganized

**Comment by stragu** [comment] 2017-11-11 12:53
I agree that that would make more sense as a default. Audio releases and whole seasons of shows would benefit from that, and it makes finding specific files in a large group a whole lot easier.

We could still have the option to sort by size somewhere, but I can't really think of why anyone would prefer that over the other. (Except to have the main file located at the tail end of the list, so watching a movie is not followed by playing e.g. video samples...)

**Comment by bnjmnt4n** [comment] 2018-01-18 14:04
Closing this as a duplicate of #1185.

**Closed by bnjmnt4n** 2018-01-18 14:04 UTC
