### ISSUE TITLE
No Control for maxDownload and uploadSpeed

### ISSUE THREAD

**Issue by sahiljain2497** [webtorrent/webtorrent-desktop#1287] opened 2017-12-12 20:55 UTC
Version 0.18.0 (0.98.5) (64-bit)
Windows 8.1
I wanted to limit down the upload speed to minimum
No option available

**Comment by bnjmnt4n** [comment] 2018-01-18 13:46
Closing as a duplicate of #435.

**Closed by bnjmnt4n** 2018-01-18 13:46 UTC
