### ISSUE TITLE
WebTorrent begins to freeze in loading when internet speed is 1GB/s

### ISSUE THREAD

**Issue by IvanMurzak** [webtorrent/webtorrent-desktop#1910] opened 2020-12-29 19:46 UTC
Version 0.24.0 (0.108.6 (x64)
Windows 10 Pro

Everything was fine until I updated my internet connection to 1GB/s, I tried qBitTorrent - works fine on full speed 1GB. 
WebTorrent begins to freeze in loading when the internet speed is 1GB/s.
Looks like it can't handle memory on the fly. I'm saving on HDD it not so fast, but I have 32gb RAB memory and my video file what I'm loading usually is less than 3GB. I mean it could be fully stored in RAM until be saved to HDD.
Helps just multiple relaunching WebTorrent app. After a single relaunch, it helps just for ~10 seconds and stuck again.

**What did you expect to happen?**
Loading without freezing downloading thread.

**Comment by alxhotel** [comment] 2020-12-30 12:11
Duplicate of #1782

**Closed by alxhotel** 2020-12-30 12:11 UTC
