### ISSUE TITLE
mass mark of files

### ISSUE THREAD

**Issue by Jhonyeee0** [webtorrent/webtorrent-desktop#1763] opened 2019-12-19 09:56 UTC
Please add a mass mark of files before downloading the torrent. This is necessary if there are a lot of files in the torrent. Now I have to manually click a lot of ticks if I only need 1 file out of 10, for example.

**Comment by hicom150** [comment] 2019-12-19 17:40
Possible duplicate of  #1330

**Closed** 2019-12-19 17:46 UTC
Labels: enhancement
