### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by jony0008** [webtorrent/webtorrent-desktop#1444] opened 2018-08-03 04:21 UTC
Please use a platform to translate webtorrent. It would be great to have it in many languages.

**Comment by feross** [comment] 2018-08-04 07:33
Thanks for the suggestion. This is a duplicate of https://github.com/webtorrent/webtorrent-desktop/issues/371 You can follow the progress there.

**Closed by feross** 2018-08-04 07:33 UTC
