### ISSUE TITLE
Support airplay with pin code

### ISSUE THREAD

**Issue by meded90** [webtorrent/webtorrent-desktop#1899] opened 2020-09-19 19:50 UTC
Please use this library for connect with auth pin code 
https://github.com/evandcoleman/node-appletv

**Comment by feross** [comment] 2020-11-24 02:27
Oh, actually this is a duplicate of: https://github.com/webtorrent/webtorrent-desktop/issues/1339

**Closed by feross** 2020-11-24 02:27 UTC
