### ISSUE TITLE
speed limiter option

### ISSUE THREAD

**Issue by Gammer20** [webtorrent/webtorrent-desktop#1820] opened 2020-06-07 14:33 UTC
**What version of WebTorrent Desktop are you using?**

**What operating system and version?**

**What problem do you want to solve?**

**What do you think is the correct solution to this problem?**

**Are you willing to submit a pull request to implement this change?**

**Comment by alxhotel** [comment] 2020-06-07 15:20
Duplicate of #435

**Closed by alxhotel** 2020-06-07 15:20 UTC
