### ISSUE TITLE
Custom Tracker Issue

### ISSUE THREAD

**Issue by valinux** [webtorrent/webtorrent-desktop#1337] opened 2018-03-08 02:49 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Current
**What operating system and version?**
Windows 10
**What did you do?**
I created my own tracker with my own URL and created my own file with advanced option with my tracker on it.
**What did you expect to happen?**
I would like for web-torrent Desktop to stop adding its default trackers on advanced settings to my new torrent files that i create and only add my custom UDP and WSS url and nothing extra by default. 
**What actually happened?**
magnet:xt=urn:d&dn=myfile.mp4&tr=udp%3A%2F%2Ftracker.mywebsite.com%3A8000&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com

i removed those trackers from my advanced settings when i created this torrent file but they are showing up when i copy the magnet link from webtorrent-desktop. 

&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com

**Comment by qqdaiyu55** [comment] 2018-04-16 10:26
Modify `/src/render/pages/create-torrent-page.js` line 55, 
```
const trackers = 'udp:\\mytracker\nwss:\\mytracker'
```

**Comment by feross** [comment] 2018-04-20 09:14
I agree that this is a bit confusing.

We need to add the wss:// trackers or else torrents won't be made available to web browsers, but I agree that you should be able to get the original torrent file as you requested it to be made when you "Right Click > Save Torrent File..." or "Right Click > Copy Magnet Link to Clipboard".

**Comment by feross** [comment] 2018-05-11 00:48
I just realized this is a duplicate of https://github.com/webtorrent/webtorrent-desktop/issues/1024

**Closed by feross** 2018-05-11 00:48 UTC
