### ISSUE TITLE
First npm install give TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function

### ISSUE THREAD

**Issue by martinsangdo** [webtorrent/webtorrent-desktop#1862] opened 2020-08-17 10:33 UTC
I am clone webtorrent source for first time.
Type "npm install", there is error:
> electron-chromedriver@9.0.0 install /Users/sangdt/Documents/Source/Electron/webtorrent-desktop/node_modules/electron-chromedriver
> node ./download-chromedriver.js

internal/util.js:206
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:206:11)
    at Object.<anonymous> (/Users/xxx/Documents/Source/Electron/webtorrent-desktop/node_modules/electron-chromedriver/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sangdt/Documents/Source/Electron/webtorrent-desktop/node_modules/electron-chromedriver/download-chromedriver.js:4:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@9.0.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@9.0.0 install script.

---
My config:
npm --version: 5.5.1
node --version: v9.0.0

**Comment by hicom150** [comment] 2020-08-17 19:58
I noticed that the version of node you are using is outdated 😅
Could you try with at least node 10.x and check if the error persists?

**Comment by dsernst** [comment] 2020-10-10 07:15
If upgrading node doesn’t help, I’d next try wiping the `node_modules/` folder with `rm -rf node_modules` and then try redoing `npm install` to see if it reproduces every time.

**Comment by feross** [comment] 2020-11-24 03:02
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨

**Closed by feross** 2020-11-24 03:02 UTC
