### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KovalevArtem** [webtorrent/webtorrent-desktop#1881] opened 2020-04-26 20:17 UTC
It is sad that the service is only in English - I propose to translate.
I am ready to help in the translation into Russian.
(For example, you can use Weblate, Crowdin, or any other service. Free for open source projects.)

**Comment by alxhotel** [comment] 2020-10-28 01:06
Duplicate of #1348

**Closed by alxhotel** 2020-10-28 01:06 UTC
