### ISSUE TITLE
Not Opening in vlc via web torrent 

### ISSUE THREAD

**Issue by hamzakafil** [webtorrent/webtorrent-desktop#1858] opened 2020-08-08 14:42 UTC
when I first install this web torrent the file opening in vlc was working but after updating my vlc it is not working.
![Screenshot (34)](https://user-images.githubusercontent.com/18714409/89713144-3df21180-d9af-11ea-9a1c-2e1392538db9.png)

**Comment by hicom150** [comment] 2020-08-08 21:01
Thank you @hamzakafil for the report! 👍
The issue is already fixed in #1850 so it should be published in the next release, hopefully soon 😉

**Closed by hicom150** 2020-08-08 21:01 UTC
