### ISSUE TITLE
Constantly Crashing on Back Arrow

### ISSUE THREAD

**Issue by ernestorendon** [webtorrent/webtorrent-desktop#1570] opened 2019-04-19 17:07 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
WebTorrent 0.20.0 (0.99.3)

**What operating system and version?**
MacOS Mojave 10.14.2 // MacBook Pro 15" mid 2015

**What did you do?**
I dropped in a magnet link to a series and had it load up in the application, and it works fine for clicking on one episode to play in VLC; but after the episode ends, I'd have to go back into the WebTorrent desktop application, and every single time I click the "Back" button to bring me back to the episode selecting screen, the application crashes every time, without fail.

**What did you expect to happen?**
Normally, I'd expect the application to simply go back to the previous screen, allowing me to select and play the next episode.

**What actually happened?**
No less than 7 times, the back button has simply crashed the program entirely, having me re-open it, then select the next episode after the application is re-opened.

**Comment by ppshobi** [comment] 2019-04-20 10:55
Confirmed, the same issue happened in my case as well.

**Comment by andersfischernielsen** [comment] 2019-04-30 09:45
It seems to be after playing any file, no matter whether through VLC or WebTorrent itself. 
In the VLC case, after quitting VLC WebTorrent crashes.

**Comment by andersfischernielsen** [comment] 2019-05-08 02:10
Strange.. When running the app using `npm run start` everything works as expected, no crashes. 
As soon as I `npm run package` the app and run the packaged app, the crashing is back.

**Comment by andersfischernielsen** [comment] 2019-05-08 02:28
It seems like one of the dependencies in `package.json` causes the crash when packaging the app. 

Running `npm-check-updates` on the repo and then downgrading the `electron` version to `^3.0.0` allows me to package the app, stream a file and then go back without issues. 

Upgrading `electron` breaks the top bar, though: 

![w](https://user-images.githubusercontent.com/5990738/57344940-3dac0a80-719d-11e9-8de4-f0cd3169cc7d.jpg)

**Comment by feross** [comment] 2019-08-16 18:46
@andersfischernielsen I wonder if the upgrade to Electron 6 has resolved these issues. Can you give this another try on the latest version of the code on `master` and report back whether this issue is fixed for you?

**Comment by javiercejudo** [comment] 2019-08-21 12:52
I had the same issue with 0.20.0 but all looks good on the latest version of the code on `master`.

**Comment by andersfischernielsen** [comment] 2019-08-21 17:44
Packaging from `master` and running the app has fixed the crashing. Thanks! 👍

**Comment by Borewit** [comment] 2019-08-21 17:47
Presumably fixed by #1641 or #1643

**Closed by Borewit** 2019-08-21 17:47 UTC
