### ISSUE TITLE
Downloads all files in multi-file torrent instead of several that I chose

### ISSUE THREAD

**Issue by ethaniel** [webtorrent/webtorrent-desktop#1095] opened 2016-12-10 17:56 UTC
Ok, so I'm downloading totally legal torrent which has around 10 big files (2gb each).
I've deselected all of them except a few.
WTD still downloads everything, even the ones I've deselected.

**Comment by wisiwig** [comment] 2016-12-22 01:45
I have the same situation. 
Win 7, webtorrent v. 0.17.2.

**Comment by thepelkus-too** [comment] 2017-01-07 02:23
Can you confirm that the files have actually downloaded and that the client isn't just allocating  space on the disk for them?

**Comment by ethaniel** [comment] 2017-01-07 05:11
Can confirm - it's an actual download.

**Comment by koji3** [comment] 2017-01-08 10:42
The same here

**Comment by BFlorry** [comment] 2017-01-13 10:31
The bug seems to be working in the following way:
After the downloading has been started, the client starts downloading the first torrent in the list. The downloading will continue even after ticking off the first one and will not start downloading other torrents until after the already started file has been fully downloaded.

**Comment by feross** [comment] 2018-05-11 00:53
Duplicate of https://github.com/webtorrent/webtorrent-desktop/issues/719

**Closed by feross** 2018-05-11 00:53 UTC
Labels: bug
