### ISSUE TITLE
Slow downs and stuttering, while downloading

### ISSUE THREAD

**Issue by Rhoaki** [webtorrent/webtorrent-desktop#1633] opened 2019-08-03 20:21 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0 (0.98.21) (64-bit)

**What operating system and version?**
Windows 10 Home (64-Bit)

**What did you do?**
Downloading a Torrent.

**What did you expect to happen?**
While downloading, no performance issues with Windows.

**What actually happened?**
While it was downloading, the mouse stutters, the sound stutters as well and it was feeling sluggish to move the mouse around. The sound, while watching a video, had slow downs all the time and it sounded like, the sound has been stretched at many parts. After the download reached 100% or pausing the download, the stuttering and slow downs stopped.

Maybe the slow downs of the sound may caused by the Software called "Realtek Audio Manager"?

_Here are informations about the audio driver I have installed:_
Version 6.0.1.8581 | DirectX 12.0 | HD Audio | Audiocodec: ALC233

**Comment by feross** [comment] 2019-08-03 23:50
Duplicate of https://github.com/webtorrent/webtorrent/issues/1026

**Closed by feross** 2019-08-03 23:50 UTC
