### ISSUE TITLE
[Feature Request] Set Download location for each torrent

### ISSUE THREAD

**Issue by xKeiro** [webtorrent/webtorrent-desktop#1238] opened 2017-09-11 10:58 UTC
As of now there's 2 main features missing from WebTorrent in order for me to truly get out what I want from it, and this is one of them. (the other one is persistent RSS feeds and auto download from them)

**Current situation**
As of now you can set a default download directory where every torrent gets downloaded

**What I would like to see** 
On top a the already existing default directory I would like to be able to set custom location on a torrent to torrent basis. A pop-up would be nice after adding a torrent file/magnet link that let's you set a custom location (preferably remember previously used locations as well)

**Why?** 
The current 1 folder for all the torrents is messy, with multiple/custom folder support you can stay organised. 

**Extra**
If you want to enhance this feature even further it would be nice to introduce "labels" (or categories) so you could create a label/category with it's own setting, stick that label to a torrent and then it would use that label's settings.

**Comment by bnjmnt4n** [comment] 2018-01-21 03:30
Closing this as a duplicate of #1245.

**Closed by bnjmnt4n** 2018-01-21 03:30 UTC
