### ISSUE TITLE
How to move a file to a new location and reseed?

### ISSUE THREAD

**Issue by ylluminarious** [webtorrent/webtorrent-desktop#1467] opened 2018-09-01 03:12 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0
**What operating system and version?**
macOS 10.13.6
**What did you do?**
Moved a downloaded file to a new location.
**What did you expect to happen?**
I should be able to reseed the file in that new location.
**What actually happened?**
The file was detected as missing.

This is a serious issue for anyone who wants to organize torrents into folders. I see no options for giving a torrent a new location. Transmission has a function called `Move Data File To...` and I see no equivalent for WebTorrent. The only workaround that exists is something like [this](https://superuser.com/questions/1161605/transmission-cant-find-downloaded-movie-in-new-location) or [this.](https://forum.transmissionbt.com/viewtopic.php?t=9776) Those workarounds become very cumbersome if one moves a file around multiple times.

**Comment by dotnetCarpenter** [comment] 2018-09-06 21:38
Duplicate of #917

**Comment by dotnetCarpenter** [comment] 2018-09-06 21:49
Fixed in #1268 but which was closed (rejected) due to developer posting images that could destroy the entire project pretty quickly.

**Comment by ylluminarious** [comment] 2018-09-07 04:40
@dotnetCarpenter Thanks for the info. I wonder, why was #1268 closed? The developer's own screenshots have no bearing nor relevance on the patches he's submitting. Accepting his patches doesn't mean that anyone condones copyright infringement.

More to the point, though: what should we do now that his solution has been flushed down the toilet?

**Comment by dotnetCarpenter** [comment] 2018-09-07 21:15
Get his PR via git clone and git checkout - merge his code into the latest
code in the master branch. If it works then create a new PR and be careful
about your images :)

If it doesn't work ,you can try to fix it or ask for help in an issue - I
doubt that webtorrent-desktop is a tag at StackOverflow.

**Comment by ylluminarious** [comment] 2018-09-08 03:47
@dotnetCarpenter Thanks for the advice. Unfortunately, I have my fingers in too many pies to get involved with this right now. I'm really only a basic user of WebTorrent at all and I had no intention of getting involved with PRs and so forth. I think this would be better left to someone with more inclination and qualification. I'll just stick with the workaround for now, I guess.

**Comment by mathiasvr** [comment] 2018-09-18 16:28
As pointed out by @dotnetCarpenter, this is a duplicate issue.
Lets track it and move the conversation to #917.

**Closed by mathiasvr** 2018-09-18 16:28 UTC
