### ISSUE TITLE
RPM build is not usable for Fedora

### ISSUE THREAD

**Issue by mariuszs** [webtorrent/webtorrent-desktop#2242] opened 2022-08-27 07:49 UTC
**What version of WebTorrent Desktop are you using?**
0.24

**What operating system and version?**
Fedora release 36 

**What happened?**
Cannot install using rpm package

```
sudo dnf install webtorrent-desktop-0.24.0-1.x86_64.rpm
Last metadata expiration check: 2:25:28 ago on sob, 27 sie 2022, 07:21:08.
Dependencies resolved.
==========================================================================================================================================================================================================
 Package                                                Architecture                               Version                                         Repository                                        Size
==========================================================================================================================================================================================================
Installing:
 webtorrent-desktop                                     x86_64                                     0.24.0-1                                        @commandline                                      66 M

Transaction Summary
==========================================================================================================================================================================================================
Install  1 Package

Total size: 66 M
Installed size: 219 M
Is this ok [y/N]: t
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
  package webtorrent-desktop-0.24.0-1.x86_64 is intended for a different operating system
```

**What did you expect to happen?**
to complete installation

**Are you willing to submit a pull request to fix this bug?**
no

**Comment by alxhotel** [comment] 2022-08-27 22:22
Duplicate of #1849

**Closed by alxhotel** 2022-08-27 22:22 UTC
