### ISSUE TITLE
hash values, gpg sigs?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [webtorrent/webtorrent-desktop#1388] opened 2018-05-11 03:12 UTC
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0-1_amd64
**What operating system and version?**
linux buntu 16.04
**What did you do?**
downloaded, looked for a hash value & signature

**What did you expect to happen?**
Find both

**What actually happened?**
Didn't.

**Comment by feross** [comment] 2018-05-20 12:29
We can generate hashes at build time and include them in an additional file in the release.

**Comment by Lew-Rockwell-Fan** [comment] 2018-05-21 19:54
A hash in a GPG SIGNED text file seems kinda basic. Guess I'll pass until then. Thanks.

**Comment by feross** [comment] 2018-05-23 00:52
The Windows and macOS binaries are code signed with a certificate that is trusted by your OS. If you wish, you can verify that in the meantime.

**Comment by feross** [comment] 2020-11-18 23:04
Duplicate of https://github.com/webtorrent/webtorrent-desktop/issues/1388

**Closed by feross** 2020-11-18 23:04 UTC
Labels: enhancement
