### ISSUE TITLE
Special filename characters will break torrents and magnets on Windows

### ISSUE THREAD

**Issue by christian-roggia** [webtorrent/webtorrent-desktop#1373] opened 2018-04-28 16:01 UTC
**What version of WebTorrent Desktop?**
Version 0.20.0 (0.98.21) (64-bit)

**What operating system and version?**
Windows 10

**What did you do?**
I opened a magnet link for a torrent that contained the special character ":" in the filename. The same result was observed with a torrent file containing a special character.

**What did you expect to happen?**
I expected the special character to be replaced with a space or an underscore.

**What actually happened?**
The file is downloaded with a broken name and the file content is never written to disk.

**Comment by feross** [comment] 2018-04-30 03:25
Thanks for reporting. This is not ideal.

**Comment by mathiasvr** [comment] 2018-10-07 15:44
@clujin I changed the big buck bunny torrent to use a colon in the filename:

[bbb_sunflower_1080p_30fps_normal_colon.torrent.zip](https://github.com/webtorrent/webtorrent-desktop/files/2454053/bbb_sunflower_1080p_30fps_normal_colon.torrent.zip)

On mac the colon is replaced with a "/", however when using a magnet link, it does not start to download.

**Comment by hicom150** [comment] 2019-07-29 13:09
Could be related to #1147

**Comment by feross** [comment] 2019-07-29 17:16
Ah, yes this is a duplicate of #1147.

**Closed by feross** 2019-07-29 17:16 UTC
Labels: bug
