### ISSUE TITLE
Suggestion!:

### ISSUE THREAD

**Issue by jgarza9788** [webtorrent/webtorrent-desktop#1251] opened 2017-10-09 06:10 UTC
i would like to control how much bandwidth streaming webtorrent-desktop takes up.
so download at 500 kb/s and seed at 250 kb/s.

this would be an awesome feature

**Comment by bnjmnt4n** [comment] 2018-01-19 04:12
Closing as duplicate of #435.

**Closed by bnjmnt4n** 2018-01-19 04:12 UTC
